services:
  bot:
    build: .
    container_name: gemma-bot
    restart: always

    env_file:
      - .env

    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - ANONYMIZED_TELEMETRY=False

    extra_hosts:
      - "host.docker.internal:host-gateway"

    # volumes:
    #   - ./chroma_db:/app/chroma_db
    #   - ./course_docs:/app/course_docs 